### ISSUE TITLE
execution FAILS

### ISSUE THREAD

**Issue by lkabuci** [aquib-sh/chartify#1]
when trying to run the app from the source it gives me this Error
```bash
Traceback (most recent call last):
  File "/path/to/chartify_app.py", line 4, in <module>
    from tkinter import font
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

**Comment by aquib-sh** [comment]
haven't tested it on Linux yet

**Comment by aquib-sh** [comment]
I should work after the latest commit

**Comment by lkabuci** [comment]
It's not working, however, the problem was with Archlinux we need to install tk manually with `sudo pacman -S tk`
